name: Checks
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: '**/*.md'

  build_pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Compile PDFs
        run: src/build.sh -o "$RUNNER_TEMP/pdfs"
